<?php if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_load-more-page-details',
        'title' => 'Load More Page Details',
        'fields' => array (
            array (
                'key' => 'field_588a0a4adb5be',
                'label' => 'Number Of Portfolio Items To Display',
                'name' => 'number_of_portfolio_items_to_display',
                'type' => 'number',
                'instructions' => 'You can select number of portfolio items on each load.',
                'default_value' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 1,
                'max' => '',
                'step' => 1,
            ),
            array (
                'key' => 'field_588a0a77db5bf',
                'label' => 'Portfolio Items Display Order',
                'name' => 'portfolio_items_display_order',
                'type' => 'select',
                'instructions' => 'Select portfolio items display order, make sure load more page and portfolio page display order should be same.',
                'choices' => array (
                    'ASC' => 'Ascending',
                    'DESC' => 'Descending',
                ),
                'default_value' => 'ASC',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-portfolio-load-more.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => -1,
    ));
    register_field_group(array (
        'id' => 'acf_testimonials-detail',
        'title' => 'Testimonials Detail',
        'fields' => array (
            array (
                'key' => 'field_58930325827e5',
                'label' => 'Author Image',
                'name' => 'author_image_testimonials',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5893035d827e6',
                'label' => 'Author Designation',
                'name' => 'author_designation_testimonials',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'me-testimonials',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => -1,
    ));
    register_field_group(array (
        'id' => 'acf_banner-details',
        'title' => 'Banner Details',
        'fields' => array (
            array (
                'key' => 'field_58948e6074be9',
                'label' => 'Select Page Banner',
                'name' => 'select_page_bnr',
                'type' => 'select',
                'choices' => array (
                    'hide' => 'Hide',
                    'left-view' => 'Left View',
                    'center-view' => 'Center View',
                    'personal-one' => 'Personal One',
                    'personal-two' => 'Personal Two (Full Screen)',
                    'personal-three' => 'Personal Three (Fixed Height)',
                    'personal-four' => 'Personal Four',
                    'slider' => 'Slider Revolution',
                ),
                'default_value' => 'hide',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_58949300c181e',
                'label' => 'Small Heading',
                'name' => 'small_heading_bnr',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'left-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'center-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-one',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-two',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-three',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-four',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58949319c181f',
                'label' => 'Large Heading',
                'name' => 'large_heading_bnr',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'left-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'center-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-one',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-two',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-three',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-four',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5894932ac1820',
                'label' => 'Description Text',
                'name' => 'description_text_bnr',
                'type' => 'textarea',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'left-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'center-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-one',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-two',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-three',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-four',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_58949340c1821',
                'label' => 'Background Image',
                'name' => 'background_image_bnr',
                'type' => 'image',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'left-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'center-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-one',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-two',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-three',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-four',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5894a06768d5d',
                'label' => 'Background Size',
                'name' => 'background_size_bnr',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'left-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'center-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-one',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-two',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-three',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-four',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'choices' => array (
                    'auto' => 'Auto',
                    'length' => 'Length',
                    'cover' => 'Cover',
                    'contain' => 'Contain',
                    'initial' => 'Initial',
                    'inherit' => 'Inherit',
                ),
                'default_value' => 'auto',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5894ab7054af9',
                'label' => 'Background Position',
                'name' => 'background_position_bnr',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'left-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'center-view',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-one',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-two',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-three',
                        ),
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'personal-four',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'choices' => array (
                    'scroll' => 'Scroll',
                    'fixed' => 'Fixed',
                    'local' => 'Local',
                    'initial' => 'Initial',
                    'inherit' => 'Inherit',
                ),
                'default_value' => 'scroll',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_589494687db8c',
                'label' => 'Slider Revolution Alias',
                'name' => 'slider_revolution_alias',
                'type' => 'text',
                'instructions' => 'Input slider revolution alias only not complete shortcode.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58948e6074be9',
                            'operator' => '==',
                            'value' => 'slider',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_blog-author-info',
        'title' => 'Blog Author Info',
        'fields' => array (
            array (
                'key' => 'field_58466a78d1a99',
                'label' => 'Author Title',
                'name' => 'author_title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58466a87d1a9a',
                'label' => 'Author Skills',
                'name' => 'author_skills',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58466a90d1a9b',
                'label' => 'Author Short Description',
                'name' => 'author_short_description',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_user',
                    'operator' => '==',
                    'value' => 'all',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_category-details',
        'title' => 'Category Details',
        'fields' => array (
            array (
                'key' => 'field_58465371a3fc1',
                'label' => 'Category Layout',
                'name' => 'category_layout',
                'type' => 'select',
                'instructions' => 'Select this category page layout.',
                'choices' => array (
                    '3-column' => '3 Columns View',
                    'single-post' => 'Single Post View With Image',
                    'single-row' => 'Single Row View',
                ),
                'default_value' => 'single-row',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_coming-soon-details',
        'title' => 'Coming Soon Details',
        'fields' => array (
            array (
                'key' => 'field_58469ffb0bdb8',
                'label' => 'Coming Soon Layout',
                'name' => 'coming_soon_layout',
                'type' => 'select',
                'choices' => array (
                    'parallax-bg' => 'Parallax Background',
                    'social-icons' => 'Social Icons',
                    'newsletter' => 'Newsletter',
                ),
                'default_value' => 'parallax-bg',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5846a0580d541',
                'label' => 'Coming Soon Logo',
                'name' => 'coming_soon_logo',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5846a0490d540',
                'label' => 'Coming Soon Heading',
                'name' => 'coming_soon_heading',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a0650d542',
                'label' => 'Coming Soon Small Caption',
                'name' => 'coming_soon_small_caption',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5846a081df2b4',
                'label' => 'Launch Date',
                'name' => 'launch_date',
                'type' => 'date_picker',
                'date_format' => 'mm/dd/yy',
                'display_format' => 'mm/dd/yy',
                'first_day' => 1,
            ),
            array (
                'key' => 'field_5846a11e839a7',
                'label' => 'Parallax Background Image',
                'name' => 'parallax_background_image_coming',
                'type' => 'image',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'parallax-bg',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5846a202a4759',
                'label' => 'Facebook',
                'name' => 'facebook_coming',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a211a475a',
                'label' => 'Twitter',
                'name' => 'twitter_coming',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a220a475b',
                'label' => 'Dribbble',
                'name' => 'dribbble_coming',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a24da475c',
                'label' => 'Linkedin',
                'name' => 'linkedin_coming',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a260a475d',
                'label' => 'Pinterest',
                'name' => 'pinterest_coming',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a26fa475e',
                'label' => 'Instagram',
                'name' => 'instagram_coming',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a318e903e',
                'label' => 'Newsletter Shortcode',
                'name' => 'newsletter_shortcode_news',
                'type' => 'text',
                'instructions' => 'Input mailpoet newsletter shortcode here.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'newsletter',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846a2ef96d5b',
                'label' => 'Background Color',
                'name' => 'background_color_social',
                'type' => 'color_picker',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'social-icons',
                        ),
                        array (
                            'field' => 'field_58469ffb0bdb8',
                            'operator' => '==',
                            'value' => 'newsletter',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'pge-coming-soon.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_contact-details',
        'title' => 'Contact Details',
        'fields' => array (
            array (
                'key' => 'field_585ba0df93ff5',
                'label' => 'Contact Form Shortcode',
                'name' => 'contact_form_shortcode_ct',
                'type' => 'text',
                'instructions' => 'Input contact form 7 shortcode recommended.',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba11393ff6',
                'label' => 'Contact Address',
                'name' => 'contact_address',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba12193ff7',
                'label' => 'Contact Email',
                'name' => 'contact_email',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba12a93ff8',
                'label' => 'Contact Phone',
                'name' => 'contact_phone',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba14993ff9',
                'label' => 'Map Latitude',
                'name' => 'map_latitude',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba15193ffa',
                'label' => 'Map Longitude',
                'name' => 'map_longitude',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba16993ffb',
                'label' => 'Map Zoom',
                'name' => 'map_zoom',
                'type' => 'number',
                'default_value' => 13,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 1,
                'max' => 24,
                'step' => 1,
            ),
            array (
                'key' => 'field_585ba17c93ffc',
                'label' => 'Map Marker',
                'name' => 'map_marker',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_585ba18893ffd',
                'label' => 'Map API Key',
                'name' => 'map_api_key',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'pge-contact.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_contact-strings',
        'title' => 'Contact Strings',
        'fields' => array (
            array (
                'key' => 'field_585ba1fbe9ec9',
                'label' => 'VISIT US',
                'name' => 'visit_us_str',
                'type' => 'text',
                'instructions' => 'You can override default string here.',
                'default_value' => 'VISIT US',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_585ba216e9eca',
                'label' => 'EMAIL',
                'name' => 'email_str_cn',
                'type' => 'text',
                'instructions' => 'You can override default string here.',
                'default_value' => 'EMAIL',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'pge-contact.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'the_content',
                1 => 'excerpt',
                2 => 'custom_fields',
                3 => 'discussion',
                4 => 'comments',
                5 => 'revisions',
                6 => 'slug',
                7 => 'author',
                8 => 'format',
                9 => 'featured_image',
                10 => 'categories',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_footer-details',
        'title' => 'Footer Details',
        'fields' => array (
            array (
                'key' => 'field_5894b58a4f4a4',
                'label' => 'Select Footer Type',
                'name' => 'select_footer_type',
                'type' => 'select',
                'instructions' => 'You can manage page footer under theme options.',
                'choices' => array (
                    'default' => 'Default',
                    'footer-diagonal' => 'Diagonal (Contact Form)',
                    'footer-plain' => 'Plain (Contact Form)',
                ),
                'default_value' => 'default',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 2,
                ),
            ),
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 3,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_header-details',
        'title' => 'Header Details',
        'fields' => array (
            array (
                'key' => 'field_58946189ac777',
                'label' => 'Header / Menu Type',
                'name' => 'header_menu_type',
                'type' => 'select',
                'instructions' => 'You can select menu style for your page.',
                'choices' => array (
                    'default' => 'Default',
                    'default-transparent' => 'Default Transparent',
                    'header-3d' => '3D Menu',
                    'header-hamburg' => 'Hamburg Menu',
                    'simple-logo' => 'Simple Logo',
                ),
                'default_value' => 'default',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_58946189style',
                'label' => 'Header / Menu Style',
                'name' => 'header_menu_style',
                'type' => 'select',
                'instructions' => 'You can select menu color style for your page.',
                'choices' => array (
                    'dark' => 'Dark',
                    'light' => 'Light'
                ),
                'default_value' => 'dark',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 2,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 3,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_page-details',
        'title' => 'Page Details',
        'fields' => array (
            array (
                'key' => 'field_587decf53ac92',
                'label' => 'Page Layout',
                'name' => 'page_layout',
                'type' => 'select',
                'choices' => array (
                    'container' => 'Container',
                    'full-width' => 'Full Width (VC recommended)',
                ),
                'default_value' => 'container',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_587ded2c3ac93',
                'label' => 'Hide Page Title',
                'name' => 'hide_page_title',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_587decf53ac92',
                            'operator' => '==',
                            'value' => 'container',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'yes' => 'Yes',
                    'no' => 'No',
                ),
                'default_value' => 'no',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_587ded463ac94',
                'label' => 'Page Classes',
                'name' => 'page_classes',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'side',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_portfolio-banner',
        'title' => 'Portfolio Banner',
        'fields' => array (
            array (
                'key' => 'field_5846d655963ec',
                'label' => 'Banner Background Image',
                'name' => 'banner_background_image_portfolio',
                'type' => 'image',
                'instructions' => 'Leave banner image empty and you will get rid of banner area.',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5846d67e963ed',
                'label' => 'Banner Large Heading',
                'name' => 'banner_large_heading_portfolio',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d693963ee',
                'label' => 'Banner Small Caption',
                'name' => 'banner_small_caption_portfolio',
                'type' => 'textarea',
                'instructions' => 'Line break tag is allowed here.',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'html',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_portfolio-details',
        'title' => 'Portfolio Details',
        'fields' => array (
            array (
                'key' => 'field_5885f05726f96',
                'label' => 'Portfolio Item Width',
                'name' => 'portfolio_item_width',
                'type' => 'select',
                'instructions' => 'Item width won\'t be applied in carousel view.',
                'choices' => array (
                    'width-33' => '1/3 By Width',
                    'width-50' => '1/2 By Width',
                    'width-66' => '2/3 By Width',
                    'width-100' => 'Full Width',
                ),
                'default_value' => 'width-33',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5846d1b1b185c',
                'label' => 'Portfolio Layout',
                'name' => 'portfolio_layout',
                'type' => 'select',
                'choices' => array (
                    'layout-one' => 'Layout One',
                    'layout-two' => 'Layout Two',
                    'layout-three' => 'Layout Three',
                    'layout-one-pop' => 'Popup Layout One',
                    'layout-two-pop' => 'Popup Layout Two',
                    'layout-three-pop' => 'Popup Layout Three',
                ),
                'default_value' => 'layout-one',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5846d13169452',
                'label' => 'Role',
                'name' => 'role_portfolio',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d14869453',
                'label' => 'Technology',
                'name' => 'technology_portofolio',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d15e69454',
                'label' => 'Client',
                'name' => 'client_portfolio',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d16f69455',
                'label' => 'Year',
                'name' => 'year_portfolio',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d18269456',
                'label' => 'Project Link',
                'name' => 'project_link',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d1f0eafd9',
                'label' => 'Project Right Image',
                'name' => 'project_right_image',
                'type' => 'image',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5846d1b1b185c',
                            'operator' => '==',
                            'value' => 'layout-one',
                        ),
                        array (
                            'field' => 'field_5846d1b1b185c',
                            'operator' => '==',
                            'value' => 'layout-one-pop',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5846d219b8e20',
                'label' => 'Project Images',
                'name' => 'project_images',
                'type' => 'repeater',
                'instructions' => 'To complete a row you have to set 12 columns for all images in a row like: 4 + 5 + 3 = 1 Row',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5846d1b1b185c',
                            'operator' => '==',
                            'value' => 'layout-two',
                        ),
                        array (
                            'field' => 'field_5846d1b1b185c',
                            'operator' => '==',
                            'value' => 'layout-three',
                        ),
                        array (
                            'field' => 'field_5846d1b1b185c',
                            'operator' => '==',
                            'value' => 'layout-two-pop',
                        ),
                        array (
                            'field' => 'field_5846d1b1b185c',
                            'operator' => '==',
                            'value' => 'layout-three-pop',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'sub_fields' => array (
                    array (
                        'key' => 'field_5846d4536b081',
                        'label' => 'Add Image',
                        'name' => 'add_image_s',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_5846d4626b082',
                        'label' => 'Image Column Size',
                        'name' => 'image_column_size',
                        'type' => 'number',
                        'column_width' => '',
                        'default_value' => 4,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 1,
                        'max' => 12,
                        'step' => 1,
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Images',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_portfolio-strings',
        'title' => 'Portfolio Strings',
        'fields' => array (
            array (
                'key' => 'field_5846d5f9bcc34',
                'label' => 'Note:',
                'name' => '',
                'type' => 'message',
                'message' => 'You can override all string values for your project below:',
            ),
            array (
                'key' => 'field_5846d56b21c7e',
                'label' => 'Description',
                'name' => 'description_string',
                'type' => 'text',
                'default_value' => 'Description',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d58d21c7f',
                'label' => 'Role',
                'name' => 'role_string',
                'type' => 'text',
                'default_value' => 'Role',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d5a121c80',
                'label' => 'Technology',
                'name' => 'technology_string',
                'type' => 'text',
                'default_value' => 'Technology',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d5b321c81',
                'label' => 'Client',
                'name' => 'client_string',
                'type' => 'text',
                'default_value' => 'Client',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d5c721c82',
                'label' => 'Year',
                'name' => 'year_string',
                'type' => 'text',
                'default_value' => 'Year',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5846d5d921c83',
                'label' => 'Launch',
                'name' => 'launch_string',
                'type' => 'text',
                'default_value' => 'Launch',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
} ?>